sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QX9TYp9/lIbON600WjOJyzukDik+KAnSk1OEEnfYkrweUIy9A0a7xAiIbTB5RFA2tjQR58YGjAxAITEcDUZKbHXRhGk8eV5mzfnt9nMtm2++6D2niBfgNWzErcNL6rTFyZzvh/xyOT8ib8Kn9hUsUSRKTwZ85O8A9nWgyJBwOq7OpH8kXRdv4cE7ZFrIZRefNeP1djlpdycmHLEf7WvMM81Pcfias+lzzLZg8pwauYLL+/q9buCeUqwsSBGhLFej8ARyHZL0Tep0QxdUQKz3hts5SmwGb76WVv6d0IUG9rTF1uYNhHCLmX27KUBAXdWVjirq2Gm9GBS0oV+pyF1F6uhA8ugEH3i2tpZrRNY+aPgj1iEkiaZQJREINASHbKuPNKIbr6jyCWRSyDm50obfdNw0femO9i7QYfCn4QLKNPmF3jQmCLL3bhrRf4aPpt8jvHtLYtGksU3OW24EjuzSMN2ZKMhaElzqouMw1R/Kgd0kMQ/yWvOBypNP7tmJiVT7TVxg5tbBSy3hmIq67+lTU0MrOato5/k8BuhFJH3T3KsNjMjZ3D8jMCaCqLOgAnuw+nPRBJCW2VCEooB+Md87krcaFj4U5q86Zo9XaiitJqluOK9mn8DpxkIptpD4ukMqqoTOZRTJVomCsZQFE1Tna9v5Rb14ENqyeNzhc5Xauvo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Grand-Canyon-of-Arizona-How-to-See-It_2394
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy